apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: training-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-app
  template:
    metadata:
      labels:
        app: training-app
    spec:
      containers:
        - name: web-container
          image: nginx:alpine
          envFrom:
            - configMapRef:
                name: app-config